export const FILL_STARSHIPS = 'FILL_STARSHIPS';
export const FETCH_STARSHIPS_ASYNC = 'FETCH_STARSHIPS_ASYNC';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';
